<?php

namespace ConferenceBundle\Repository;

/**
 * BreakRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BreakRepository extends \Doctrine\ORM\EntityRepository
{
}
