<?php

namespace ConferenceBundle\Repository;

/**
 * lectureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lectureRepository extends \Doctrine\ORM\EntityRepository
{
}
